CentOS 8 gdb-rhbz1187581-power8-regs-7of7.patch
From FEDORA_PATCHES Mon Sep 17 00:00:00 2001
From: Jan Kratochvil <jan.kratochvil@redhat.com>
Date: Thu, 9 Aug 2018 17:18:49 +0200
Subject: gdb-rhbz1187581-power8-regs-7of7.patch

;; Add GDB support to access/display POWER8 registers (IBM, RH BZ 1187581).

commit a7f25a84f4cc1df5248c46346337f19a2a66af5a
Author: Simon Marchi <simon.marchi@ericsson.com>
Date:   Mon Aug 6 16:54:47 2018 -0400

    Fix compilation failure in remote.c

    A recent patch introduced a few of these:

    /home/emaisin/src/binutils-gdb/gdb/remote.c:12862:19: error: format not a string literal and no format arguments [-Werror=format-security]
         error (err_msg);
                       ^

    Fix them by replacing the call to error with

      error ("%s", err_msg);

    gdb/ChangeLog:

            * remote.c (remote_target::download_tracepoint): Fix format
            string errors.

+2018-08-06  Simon Marchi  <simon.marchi@ericsson.com>
+
+	* remote.c (remote_target::download_tracepoint): Fix format
+	string errors.
+
 2018-08-06  Pedro Franco de Carvalho  <pedromfc@linux.ibm.com>

 	* tracefile.c: Include common/byte-vector.h.